from __future__ import annotations

# Post-processing module is intentionally empty.
# Velocity, pressure, mesh, and Cp visualizations are created manually in ParaView.
# Convergence and aggregate plots are generated by physics/analysis.py.
