from __future__ import annotations

import dataclasses
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

# ── Config generation ──


@dataclasses.dataclass
class SU2Config:
    """Parameters for an SU2 .cfg file for compressible RANS airfoil simulation."""

    angle_of_attack: float = 0.0
    mach_number: float = 0.15
    reynolds_number: float = 1_000_000
    reynolds_length: float = 1.0
    iterations: int = 2000
    cfl_number: float = 0.5
    cfl_adapt: bool = True
    turbulence_model: str = "SA"
    muscl_flow: str = "NO"
    slope_limiter_flow: str = "VENKATAKRISHNAN"
    conv_num_method_flow: str = "ROE"
    screen_output: str = "ITER, RMS_DENSITY, LIFT, DRAG"

    def write(self, path: Path) -> None:
        """Generate a .cfg file at path."""
        tag = str(int(self.angle_of_attack))
        lines = [
            f"% ------ CONFIG FILE (auto-generated by SU2Config) ------",
            f"",
            f"% --- SOLVER DEFINITIONS ---",
            f"SOLVER= RANS",
            f"KIND_TURB_MODEL= {self.turbulence_model}",
            f"MATH_PROBLEM= DIRECT",
            f"RESTART_SOL= NO",
            f"",
            f"% --- FREESTREAM DEFINITIONS ---",
            f"MACH_NUMBER= {self.mach_number}",
            f"AOA= {self.angle_of_attack:.2f}",
            f"REYNOLDS_NUMBER= {self.reynolds_number}",
            f"REYNOLDS_LENGTH= {self.reynolds_length}",
            f"",
            f"% --- THERMODYNAMIC PROPERTIES ---",
            f"FLUID_MODEL= STANDARD_AIR",
            f"GAMMA_VALUE= 1.4",
            f"GAS_CONSTANT= 287.05",
            f"FREESTREAM_TEMPERATURE= 288.15",
            f"FREESTREAM_PRESSURE= 101325.0",
            f"",
            f"% --- BOUNDARY CONDITIONS ---",
            f"MARKER_FAR= ( farfield )",
            f"MARKER_HEATFLUX= ( airfoil, 0.0 )",
            f"MARKER_MONITORING= ( airfoil )",
            f"",
            f"% --- NUMERICAL METHODS ---",
            f"NUM_METHOD_GRAD= GREEN_GAUSS",
            f"CONV_NUM_METHOD_FLOW= {self.conv_num_method_flow}",
            f"CONV_NUM_METHOD_TURB= SCALAR_UPWIND",
            f"MUSCL_FLOW= {self.muscl_flow}",
            f"SLOPE_LIMITER_FLOW= {self.slope_limiter_flow}",
            f"MUSCL_TURB= NO",
            f"TIME_DISCRE_FLOW= EULER_IMPLICIT",
            f"",
            f"% --- ITERATIVE CONTROLS ---",
            f"ITER= {self.iterations}",
            f"CFL_NUMBER= {self.cfl_number}",
            f"CFL_ADAPT= {'YES' if self.cfl_adapt else 'NO'}",
            f"CFL_ADAPT_PARAM= ( 0.01, 5.0, 1.1, 25.0 )",
            f"",
            f"% --- CONVERGENCE CRITERIA ---",
            f"CONV_FIELD= RMS_DENSITY",
            f"CONV_RESIDUAL_MINVAL= -8",
            f"CONV_STARTITER= 10",
            f"",
            f"% --- LINEAR SOLVER ---",
            f"LINEAR_SOLVER= FGMRES",
            f"LINEAR_SOLVER_PREC= ILU",
            f"LINEAR_SOLVER_ERROR= 1E-6",
            f"LINEAR_SOLVER_ITER= 10",
            f"",
            f"% --- MULTIGRID ---",
            f"MGLEVEL= 0",
            f"",
            f"% --- OUTPUT ---",
            f"MESH_FORMAT= SU2",
            f"MESH_FILENAME= mesh.su2",
            f"TABULAR_FORMAT= CSV",
            f"CONV_FILENAME= history",
            f"VOLUME_FILENAME= flow_results_{tag}",
            f"SURFACE_FILENAME= surface_flow_{tag}",
            f"OUTPUT_WRT_FREQ= {self.iterations}",
            f"HISTORY_WRT_FREQ_INNER= 1",
            f"SCREEN_OUTPUT= ( {self.screen_output} )",
            f"HISTORY_OUTPUT= ( INNER_ITER, RMS_RES, AERO_COEFF )",
            f"OUTPUT_FILES= (RESTART, PARAVIEW)",
            f"",
        ]
        path.write_text("\n".join(lines))


# ── 3D Config ──


@dataclasses.dataclass
class SU2Config3D:
    """Parameters for SU2 .cfg for 3D compressible RANS wing simulation."""

    angle_of_attack: float = 4.0
    mach_number: float = 0.15
    reynolds_number: float = 1_000_000
    reynolds_length: float = 1.0
    iterations: int = 3000
    cfl_number: float = 0.1  # Reduced from 0.5
    cfl_adapt: bool = True
    turbulence_model: str = "SA"
    muscl_flow: str = "NO"

    def write(self, path: Path) -> None:
        tag = str(int(self.angle_of_attack))
        lines = [
            "% ------ CONFIG FILE (3D, auto-generated by SU2Config3D) ------",
            "",
            "% --- SOLVER DEFINITIONS ---",
            "SOLVER= RANS",
            f"KIND_TURB_MODEL= {self.turbulence_model}",
            "MATH_PROBLEM= DIRECT",
            "RESTART_SOL= NO",
            "",
            "% --- FREESTREAM DEFINITIONS ---",
            f"MACH_NUMBER= {self.mach_number}",
            f"AOA= {self.angle_of_attack:.2f}",
            f"REYNOLDS_NUMBER= {self.reynolds_number}",
            f"REYNOLDS_LENGTH= {self.reynolds_length}",
            "",
            "% --- THERMODYNAMIC PROPERTIES ---",
            "FLUID_MODEL= STANDARD_AIR",
            "GAMMA_VALUE= 1.4",
            "GAS_CONSTANT= 287.05",
            "FREESTREAM_TEMPERATURE= 288.15",
            "FREESTREAM_PRESSURE= 101325.0",
            "",
            "% --- BOUNDARY CONDITIONS ---",
            "MARKER_FAR= ( farfield )",
            "MARKER_HEATFLUX= ( airfoil, 0.0 )",
            "MARKER_MONITORING= ( airfoil )",
            "",
            "% --- NUMERICAL METHODS ---",
            "NUM_METHOD_GRAD= GREEN_GAUSS",
            "CONV_NUM_METHOD_FLOW= ROE",
            "CONV_NUM_METHOD_TURB= SCALAR_UPWIND",
            f"MUSCL_FLOW= {self.muscl_flow}",
            "SLOPE_LIMITER_FLOW= VENKATAKRISHNAN",
            "MUSCL_TURB= NO",
            "TIME_DISCRE_FLOW= EULER_IMPLICIT",
            "",
            "% --- ITERATIVE CONTROLS ---",
            f"ITER= {self.iterations}",
            f"CFL_NUMBER= {self.cfl_number}",
            f"CFL_ADAPT= {'YES' if self.cfl_adapt else 'NO'}",
            "CFL_ADAPT_PARAM= ( 0.01, 5.0, 1.1, 25.0 )",
            "",
            "% --- CONVERGENCE CRITERIA ---",
            "CONV_FIELD= RMS_DENSITY",
            "CONV_RESIDUAL_MINVAL= -6",
            "CONV_STARTITER= 10",
            "",
            "% --- LINEAR SOLVER ---",
            "LINEAR_SOLVER= FGMRES",
            "LINEAR_SOLVER_PREC= ILU",
            "LINEAR_SOLVER_ERROR= 1E-6",
            "LINEAR_SOLVER_ITER= 10",
            "",
            "% --- MULTIGRID ---",
            "MGLEVEL= 0",
            "",
            "% --- OUTPUT ---",
            "MESH_FORMAT= SU2",
            "MESH_FILENAME= mesh.su2",
            "TABULAR_FORMAT= CSV",
            "CONV_FILENAME= history",
            f"VOLUME_FILENAME= flow_3d_{tag}",
            f"SURFACE_FILENAME= surface_3d_{tag}",
            "OUTPUT_WRT_FREQ= 100",
            f"HISTORY_WRT_FREQ_INNER= 1",
            "SCREEN_OUTPUT= ( ITER, RMS_DENSITY, LIFT, DRAG )",
            "HISTORY_OUTPUT= ( INNER_ITER, RMS_RES, AERO_COEFF )",
            "OUTPUT_FILES= (RESTART, PARAVIEW)",
            "",
        ]
        path.write_text("\n".join(lines))


# ── Results container ──


@dataclasses.dataclass
class SU2Results:
    """Parsed results from an SU2_CFD run."""

    cd: float = 0.0
    cl: float = 0.0
    cmz: float = 0.0
    converged: bool = False
    iterations: int = 0
    history: list[dict] = dataclasses.field(default_factory=list)

    def to_dict(self) -> dict:
        return dataclasses.asdict(self)


# ── Solver interface ──


class SU2Solver:
    """Invoke SU2_CFD and collect results."""

    def __init__(self, su2_cfd: str = "SU2_CFD", workdir: Optional[Path] = None):
        self.su2_cfd = su2_cfd
        self.workdir = workdir or Path(tempfile.mkdtemp())

    def run(
        self,
        config: SU2Config,
        mesh_file: Path,
        output_dir: Path,
        timeout: Optional[int] = None,
    ) -> SU2Results:
        """Run SU2_CFD with the given config and mesh.

        Args:
            config: SU2Config dataclass
            mesh_file: Path to the .su2 mesh file
            output_dir: Directory for output (config, results, solution files)
            timeout: Optional timeout in seconds
        """
        output_dir = Path(output_dir).resolve()
        output_dir.mkdir(parents=True, exist_ok=True)

        # Write config to output directory
        cfg_path = output_dir / "config.cfg"
        config.write(cfg_path)

        # Copy mesh to output directory (skip if already there)
        mesh_local = output_dir / "mesh.su2"
        if mesh_file.resolve() != mesh_local.resolve():
            shutil.copy2(mesh_file, mesh_local)

        cmd = [self.su2_cfd, str(cfg_path)]
        print(f"  Executing SU2_CFD (up to {config.iterations} iterations)...")

        try:
            proc = subprocess.run(
                cmd,
                cwd=str(output_dir),
                capture_output=True,
                text=True,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            print("  SU2_CFD timed out")
            return SU2Results()

        return self._parse_results(proc, output_dir)

    def _normalize_header(self, raw_header: str) -> list[str]:
        """Parse and normalize CSV header, stripping whitespace and quotes."""
        return [h.strip().strip('"').strip() for h in raw_header.split(",")]

    def _parse_screen_cl_cd(
        self, stdout: str
    ) -> tuple[Optional[float], Optional[float]]:
        """Extract CL and CD from the last screen output line."""
        import re
        # SU2 screen output format (compressible RANS):
        # " 99| -1.53e+00|  0.0000|  0.0081"
        # Capture pipe-delimited values after the last header row
        lines = stdout.strip().split("\n")
        for line in reversed(lines):
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 4:
                try:
                    # parts[0] is iteration, rest are values
                    cd_val = float(parts[-1])
                    cl_val = float(parts[-2])
                    return cl_val, cd_val
                except (ValueError, IndexError):
                    continue
        return None, None

    def _parse_results(
        self, proc: subprocess.CompletedProcess, workdir: Path
    ) -> SU2Results:
        results = SU2Results()
        stdout = proc.stdout
        stderr = proc.stderr

        if proc.returncode != 0:
            print(f"  [SU2 exited with code {proc.returncode}]")
            for line in (stderr or "").strip().split("\n")[-5:]:
                if line.strip():
                    print(f"  STDERR: {line.strip()}")
            return results

        # Check convergence
        results.converged = (
            "Convergence reached" in stdout or "convergence" in stdout.lower()
        )

        # Column name mapping (handles various SU2 versions)
        col_map = {
            "ITER": "ITER",
            "Inner_Iter": "ITER",
            "INNER_ITER": "ITER",
            "DRAG": "DRAG",
            "CD": "DRAG",
            "cd": "DRAG",
            "LIFT": "LIFT",
            "CL": "LIFT",
            "cl": "LIFT",
            "MOMENT": "MOMENT",
            "CMZ": "MOMENT",
            "Cmz": "MOMENT",
        }

        # Parse history CSV
        hist_file = workdir / "history.csv"
        if hist_file.exists():
            lines = hist_file.read_text().strip().split("\n")
            if len(lines) > 1:
                header = self._normalize_header(lines[0])
                n_cols = len(header)

                # Last line gives converged CL/CD
                last_entry: Optional[dict] = None

                for line in lines[1:]:
                    vals = [v.strip() for v in line.split(",")]
                    if len(vals) == n_cols:
                        entry_orig = dict(zip(header, vals))
                        entry = {
                            col_map.get(k, k): v for k, v in entry_orig.items()
                        }
                        results.history.append(entry)
                        last_entry = entry

                if last_entry:
                    try:
                        results.iterations = int(
                            float(last_entry.get("ITER", 0))
                        )
                        cd = last_entry.get("DRAG")
                        cl = last_entry.get("LIFT")
                        if cd is not None:
                            results.cd = float(cd)
                        if cl is not None:
                            results.cl = float(cl)
                    except (ValueError, TypeError):
                        pass

        # Fallback: parse SCREEN_OUTPUT if history didn't have CL/CD
        if abs(results.cd) < 1e-12 or abs(results.cl) > 1e3:
            cl, cd = self._parse_screen_cl_cd(stdout)
            if cl is not None:
                results.cl = cl
                results.cd = cd

        return results
